# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Default_config = debug
endif
ifeq ($(config),release)
  Default_config = release
endif

PROJECTS := Default

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Default:
ifneq (,$(Default_config))
	@echo "==== Building Default ($(Default_config)) ===="
	@${MAKE} --no-print-directory -C Default -f Makefile config=$(Default_config)
endif

clean:
	@${MAKE} --no-print-directory -C Default -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Default"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"